<a href="https://colab.research.google.com/github/arsalanrex/Hackerrank/blob/Python/hackerrank_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction

---



# Basic Data Types

---



# Strings

---



# Sets

---



# Math

---



# Itertools

---



# Collections

---



# Date and Time

---



# Errors and Exceptions

---



# Classes

---



# Built-Ins

---



# Python Functionals

---



# Regex and Parsing

---



In [ ]:
import re
print(bool(re.match(r'^[a-z]?[\w._-]+@[a-z]+\.[a-z]{1,3}$', input())))


sdsHYYH@sd.co
True


## Detect Floating Point Number

## Re.split()

## Group(), Groups() & Groupdict()

## Re.findall() & Re.finditer()

## Re.start() & Re.end()

## Regex Substitution

## Validating Roman Numerals

## Validating phone numbers

## Validating and Parsing Email Addresses

In [ ]:
import email.utils
import re
def checkmail(mail):
    return(bool(re.match(r'^[a-z](\w|-|\.|_)+@[a-z]+\.[a-z]{1,3}$', mail, re.I)))

for _ in range(int(input())):
    m = email.utils.parseaddr(input())
    if checkmail(m[1]): print(email.utils.formataddr(m))

2
DEXTER <dexter@hotmail.com>
DEXTER <dexter@hotmail.com>
VIRUS <virus!@variable.:p>


## Hex Color Code

In [ ]:
import re
s = ""
for _ in range(int(input())):
    s = s+input()
hex = re.findall(r'#[abcdef0-9]+(?![\s]*[{])', s, re.I)
for x in hex:
    if len(x) not in [4,7]: hex.remove(x)
print(*hex, sep="\n")

11
#BED
{
    color: #FfFdF8; background-color:#aef;
    font-size: 123px;
    background: -webkit-linear-gradient(top, #f9f9f9, #fff);
}
#Cab
{
    background-color: #ABC;
    border: 2px dashed #fff;
}
#FfFdF8
#aef
#f9f9f9
#fff
#ABC
#fff


## HTML Parser - Part 1

In [ ]:
from html.parser import HTMLParser

class HParser(HTMLParser):
    def handle_starttag(self, tag, attrs):
        print("Start : "+tag)
        for attr in attrs:
            print("-> ", end = "")
            print(*attr, sep=" > ")
    def handle_endtag(self, tag):
        print("End   : "+tag)
    def handle_startendtag(self, tag, attrs):
        print("Empty : "+tag)
        for attr in attrs:
            print("-> ", end = "")
            print(*attr, sep=" > ")

s = ""
for _ in range(int(input())):
    s += input()
parser = HParser()
parser.feed(s)

2
<html><head><title>HTML Parser - I</title></head>
<body data-modal-target class='1'><h1>HackerRank</h1><br /></body></html>
Start : html
Start : head
Start : title
End   : title
End   : head
Start : body
-> data-modal-target > None
-> class > 1
Start : h1
End   : h1
Empty : br
End   : body
End   : html


## HTML Parser - Part 2

In [ ]:
from html.parser import HTMLParser
class CustomHTMLParser(HTMLParser):
    def handle_comment(self, data):
        number_of_line = len(data.split('\n'))
        if number_of_line>1:
            print('>>> Multi-line Comment')
        else:
            print('>>> Single-line Comment')
        if data.strip():
            print(data)

    def handle_data(self, data):
        if data.strip():
            print(">>> Data")
            print(data)

parser = CustomHTMLParser()

n = int(input())

html_string = ''
for i in range(n):
    html_string += input().rstrip()+'\n'
    
parser.feed(html_string)
parser.close()

4
<!--[if IE 9]>IE9-specific content
<![endif]-->
<div> Welcome to HackerRank</div>
<!--[if IE 9]>IE9-specific content<![endif]-->
>>> Multi-line Comment
[if IE 9]>IE9-specific content
<![endif]
>>> Data
 Welcome to HackerRank
>>> Single-line Comment
[if IE 9]>IE9-specific content<![endif]


## Detect HTML Tags, Attributes and Attribute Values

In [ ]:
from html.parser import HTMLParser

class HParser(HTMLParser):
    def handle_starttag(self, tag, attrs):
        print(tag)
        for attr in attrs:
            print("-> ", end = "")
            print(*attr, sep = " > ")


s=""
for _ in range(int(input())):
    s+= input()
par = HParser()
par.feed(s)

9
<head>
<title>HTML</title>
</head> 
<object type="application/x-flash" 
  data="your-file.swf"    
  width="0" height="0">
  <!-- <param name="movie" value="your-file.swf" /> -->
  <param name="quality" value="high"/>
</object>
head
title
object
-> type > application/x-flash
-> data > your-file.swf
-> width > 0
-> height > 0
param
-> name > quality
-> value > high


## Validating UID

In [7]:
uc, d, w = 0, 0, 0
for _ in range(int(input())):
    s = list(input())
    if len(set(s)) == 10:
        uc = sum(1 for x in s if x.isupper())
        d = sum(1 for x in s if x.isdigit())
        w = sum(1 for x in s if not x.isalnum())
        print("Valid") if uc >=2 and d >=3 and w == 0 else print("Invalid")
    else: print("Invalid")

2
B1CD102354
Invalid
B1CDEF2354
Valid


## Validating Credit Card Numbers

In [2]:
import re
import itertools 
p1 = re.compile(r'^[456](\d{15}|\d{3}(\-\d{4}){3})$')
for _ in range(int(input())):
    cno = input()
    if p1.match(cno):
        cno = list(cno.replace("-", ""))
        maxcount = [len(list(x[1])) for x in itertools.groupby(cno)]
        print("Valid") if max(maxcount) < 4 else print("Invalid")
    else: print("Invalid")

6
4123456789123456
Valid
5123-4567-8912-3456
Valid
61234-567-8912-3456
Invalid
4123356789123456
Valid
5133-3367-8912-3456
Invalid
5123 - 3567 - 8912 - 3456
Invalid


## Validating Postal Codes

In [3]:
regex_integer_in_range = r"^[1-9]\d{5}$"	# Do not delete 'r'.
regex_alternating_repetitive_digit_pair = r"(\d)(?=.\1)"	# Do not delete 'r'.


import re
P = input()

print (bool(re.match(regex_integer_in_range, P)) 
and len(re.findall(regex_alternating_repetitive_digit_pair, P)) < 2)

110000
False


## Matrix Script

In [45]:
import re
n, m = map(int, input().split())
s, ans = [], ""
for _ in range(n): s.append(list(input()))
for i in range(m):
  for j in range(n): ans += s[j][i]
print (re.sub('(?<=\w)([^\w]+)(?=\w)', " ", ans))

7 3
Tsi
h%x
i #
sM 
$a 
#t%
ir!
This is Matrix#  %!


## Regex Substitution

In [47]:
import re
s = ""
for _ in range(int(input())): s+= input()+"\n"
print(re.sub(r'(?<= )(&&|\|\|)(?= )', lambda x: 'and' if x.group() == '&&' else 'or', s))

11
a = 1;
b = input();

if a + b > 0 && a - b < 0:
    start()
elif a*b > 10 || a/b < 1:
    stop()
print set(list(a)) | set(list(b)) 
#Note do not change &&& or ||| or & or |
#Only change those '&&' which have space on both sides.
#Only change those '|| which have space on both sides.
a = 1;
b = input();

if a + b > 0 and a - b < 0:
    start()
elif a*b > 10 or a/b < 1:
    stop()
print set(list(a)) | set(list(b)) 
#Note do not change &&& or ||| or & or |
#Only change those '&&' which have space on both sides.
#Only change those '|| which have space on both sides.



## Validating Roman Numerals

In [48]:
regex_pattern = r"^M{0,3}(CM|CD|D?C{0,3})(XC|XL|L?X{0,3})(IX|IV|V?I{0,3})$"	# Do not delete 'r'.

import re
print(str(bool(re.match(regex_pattern, input()))))

CDXXI
True


## Validating phone numbers

In [49]:
import re
for _ in range(int(input())):
    print("YES") if re.match(r'^[789]\d{9}$', input()) else print("NO") 

2
9587456281
YES
1252478965
NO


## Re.start() & Re.end()

In [50]:
s, p, f = input(), input(), 0
for i in range(len(s)):
    if s[i:i+len(p)] == p: 
        print((i,i+len(p)-1))
        f = 1
if f == 0: print((-1, -1))

aaadaa
aa
(0, 1)
(1, 2)
(4, 5)


# XML

---



## XML 1 - Find the Score

In [56]:
import sys
import xml.etree.ElementTree as etree

def get_attr_number(node):
    # your code goes here
    return etree.tostring(node).count(b'=')

if __name__ == '__main__':
    sys.stdin.readline()
    xml = sys.stdin.read()
    tree = etree.ElementTree(etree.fromstring(xml))
    root = tree.getroot()
    print(get_attr_number(root))

ParseError: ignored

## XML2 - Find the Maximum Depth

In [57]:
import xml.etree.ElementTree as etree

maxdepth = 0
def depth(elem, level):
    global maxdepth
    # your code goes here
    if (level == maxdepth):
        maxdepth += 1
        
    for child in elem:
        depth(child, level + 1)

if __name__ == '__main__':
    n = int(input())
    xml = ""
    for i in range(n):
        xml =  xml + input() + "\n"
    tree = etree.ElementTree(etree.fromstring(xml))
    depth(tree.getroot(), -1)
    print(maxdepth)

6
<feed xml:lang='en'>
    <title>HackerRank</title>
    <subtitle lang='en'>Programming challenges</subtitle>
    <link rel='alternate' type='text/html' href='http://hackerrank.com/'/>
    <updated>2013-12-25T12:00:00</updated>
</feed>
1


# Closures and Decorators

---



## Standardize Mobile Number Using Decorators

In [53]:
def wrapper(f):
    def fun(l):
        # complete the function
        l =  ["+91 " + i[-10:-5] + " " + i[-5:] for i in l]
        return f(sorted(l))
    return fun

@wrapper
def sort_phone(l):
    print(*sorted(l), sep='\n')

if __name__ == '__main__':
    l = [input() for _ in range(int(input()))]
    sort_phone(l) 

3
07895462130
919875641230
9195969878
+91 78954 62130
+91 91959 69878
+91 98756 41230


## Decorators 2 - Name Directory

In [54]:
import operator

def person_lister(f):
    def inner(people):
        # complete the function
        return map(f, sorted([[e[0], e[1], int(e[2]), e[3]] for e in people], 
                             key=operator.itemgetter(2)))
    return inner

@person_lister
def name_format(person):
    return ("Mr. " if person[3] == "M" else "Ms. ") + person[0] + " " 
    + person[1]

if __name__ == '__main__':
    people = [input().split() for i in range(int(input()))]
    print(*name_format(people), sep='\n')

3
Mike Thomson 20 M
Robert Bustle 32 M
Andria Bustle 30 F
Mr. Mike 
Ms. Andria 
Mr. Robert 


# Numpy
---



## Arrays

In [ ]:
import numpy

def arrays(arr):
    return numpy.array(arr, float)[::-1]

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


## Shape and Reshape

In [ ]:
import numpy
my_array = numpy.array(input().split(), int)
print (numpy.reshape(my_array,(3,3)))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Transpose and Flatten

In [ ]:
import numpy
n, _ = map(int, input().split())
arr = numpy.array([input().strip().split() for _ in range(n)], int)
print(arr.transpose(), arr.flatten(), sep = "\n" )

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


## Concatenate

In [ ]:
import numpy
n, m, _= map(int, input().strip().split())
arr1 = numpy.array([input().strip().split() for _ in range(n)], int)
arr2 = numpy.array([input().strip().split() for _ in range(m)], int)
print(numpy.concatenate((arr1, arr2), axis= 0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


## Zeros and Ones

In [ ]:
import numpy
n = list(map(int, input().split()))
print(numpy.zeros(n, dtype=numpy.int), numpy.ones(n, dtype=numpy.int), sep="\n")

3 3 3
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


## Eye and Identity

In [ ]:
import numpy
numpy.set_printoptions(legacy='1.13')
n = list(map(int, input().split()))
print(numpy.eye(n[0], n[1]))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## Array Mathematics


In [ ]:
import numpy
n, m = map(int, input().split())
a = numpy.array([input().strip().split() for _ in range(n)], int)
b = numpy.array([input().strip().split() for _ in range(n)], int)
print(a+b, a-b, a*b, a//b, a%b, a**b, sep="\n")

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


## Floor, Ceil and Rint

In [ ]:
import numpy as np
np.set_printoptions(legacy='1.13')
a = np.array([input().split()], float)
print(*np.floor(a), *np.ceil(a), *np.rint(a), sep="\n")

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


## Sum and Prod

In [ ]:
import numpy
n, _ = map(int, input().split())
arr = numpy.array([input().split() for _ in range(n)], int)
print(numpy.prod(arr.sum(axis = 0)))

2 2
1 2
3 4
24


## Min and Max

In [ ]:
import numpy
n, _ = map(int, input().split())
arr = numpy.array([input().split() for _ in range(n)], int)
print(numpy.max(arr.min(axis=1)))

4 2
2 5
3 7
1 3
4 0
3


## Mean, Var, and Std

In [ ]:
import numpy
n, _ = map(int, input().split())
arr = numpy.array([input().split() for _ in range(n)], int)
print(arr.mean(axis=1), arr.var(axis=0), round(arr.std(), 11), sep="\n")

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


## Dot and Cross

In [ ]:
import numpy
n = int(input())
arr1 = numpy.array([input().split() for _ in range(n)], int)
arr2 = numpy.array([input().split() for _ in range(n)], int)
print(numpy.dot(arr1, arr2))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


## Inner and Outer

In [ ]:
import numpy
arr1 = numpy.array(input().split(), int)
arr2 = numpy.array(input().split(), int)
print(numpy.inner(arr1, arr2), numpy.outer(arr1, arr2), sep="\n")

0 1
2 3
3
[[0 0]
 [2 3]]


## Polynomials

In [ ]:
import numpy
n = numpy.array(input().split(), float)
print(numpy.polyval(n,int(input())))

1.1 2 3
0
3.0


## Linear Algebra

In [ ]:
import numpy as np
arr = np.array([input().split() for _ in range(int(input()))], float)
print (round(np.linalg.det(arr), 2))

2
1.1 1.1
1.1 1.1
0.0


# Debugging

---



## Words Score

In [51]:
def is_vowel(letter):
    return letter in ['a', 'e', 'i', 'o', 'u', 'y']

def score_words(words):
    score = 0
    for word in words:
        num_vowels = 0
        for letter in word:
            if is_vowel(letter):
                num_vowels += 1
        if num_vowels % 2 == 0:
            score += 2
        else:
            score += 1
    return score


n = int(input())
words = input().split()
print(score_words(words))

2
hacker book
4


In [52]:
class EvenStream(object):
    def __init__(self):
        self.current = 0

    def get_next(self):
        to_return = self.current
        self.current += 2
        return to_return

class OddStream(object):
    def __init__(self):
        self.current = 1

    def get_next(self):
        to_return = self.current
        self.current += 2
        return to_return

def print_from_stream(n, stream=EvenStream()):
    stream.__init__()
    for _ in range(n):
        print(stream.get_next())


queries = int(input())
for _ in range(queries):
    stream_name, n = input().split()
    n = int(n)
    if stream_name == "even":
        print_from_stream(n)
    else:
        print_from_stream(n, OddStream())

3
odd 2
1
3
even 3
0
2
4
odd 5
1
3
5
7
9
