<a href="https://colab.research.google.com/github/arsalanrex/Hackerrank/blob/Python/hackerrank_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy
---



## Arrays

In [17]:
import numpy

def arrays(arr):
    return numpy.array(arr, float)[::-1]

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


## Shape and Reshape

In [18]:
import numpy
my_array = numpy.array(input().split(), int)
print (numpy.reshape(my_array,(3,3)))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Transpose and Flatten

In [16]:
import numpy
n, _ = map(int, input().split())
arr = numpy.array([input().strip().split() for _ in range(n)], int)
print(arr.transpose(), arr.flatten(), sep = "\n" )

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


## Concatenate

In [15]:
import numpy
n, m, _= map(int, input().strip().split())
arr1 = numpy.array([input().strip().split() for _ in range(n)], int)
arr2 = numpy.array([input().strip().split() for _ in range(m)], int)
print(numpy.concatenate((arr1, arr2), axis= 0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


## Zeros and Ones

In [16]:
import numpy
n = list(map(int, input().split()))
print(numpy.zeros(n, dtype=numpy.int), numpy.ones(n, dtype=numpy.int), sep="\n")

3 3 3
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


## Eye and Identity

In [13]:
import numpy
numpy.set_printoptions(legacy='1.13')
n = list(map(int, input().split()))
print(numpy.eye(n[0], n[1]))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## Array Mathematics


In [25]:
import numpy
n, m = map(int, input().split())
a = numpy.array([input().strip().split() for _ in range(n)], int)
b = numpy.array([input().strip().split() for _ in range(n)], int)
print(a+b, a-b, a*b, a//b, a%b, a**b, sep="\n")

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


## Floor, Ceil and Rint